language: python

sudo: required

python:

  - "3.6"

services:

  - postgresql
  - docker

install:

  - sh .travis/install.sh

before_script:

  - psql -c 'create database test_db;' -U postgres

script:

  - sh .travis/code_analyse.sh

after_success:
  - sh .travis/deploy_dockerhub.sh
  - sh .travis/deploy_heroku.sh