language: python

sudo: required

python:

  - "3.6"

services:

  - postgresql
  - docker

install:

  - pip install pipenv
  - pipenv install -d --system

before_script:

  - psql -c 'create database test_db;' -U postgres

script:

  - python manage.py test

after_success:
  - sh .travis/deploy_dockerhub.sh
  - sh .travis/deploy_heroku.sh