version: '3'

services:
  db:
    image: postgres
  web:
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    build: .
    command: gunicorn project.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db