# Generated by Django 2.1 on 2018-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('is_smoker', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
